apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: SERVICE_NAME
  namespace: NAMESPACE
  labels:
    project: SERVICE_NAME
    env: NAMESPACE
    tier: TIER
    run: RUN
    subsystem: SUBSYSTEM
spec:
  replicas: REPLICAS_COUNT
  selector:
    matchLabels:
      project: SERVICE_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        project: SERVICE_NAME
        env: NAMESPACE
        tier: TIER
        run: RUN
        subsystem: SUBSYSTEM
    spec:
      nodeSelector:
        env: NAMESPACE
      containers:
      - name: SERVICE_NAME
        image: DOCKER_IMAGE_HOST/build_v3/SERVICE_NAME:IMAGE_TAG
        imagePullPolicy: Always
COMMAND
        ports:
        - containerPort: SERVICE_PORT
        resources:
          requests:
            memory: "MINMEMORY"
            cpu: "MINCPU"
          limits:
            memory: "MAXMEMORY"
            cpu: "MAXCPU"
        envFrom:
        - configMapRef:
            name: publicenv
VARIABLE-APP
      imagePullSecrets:
        - name: registry-secret
#      hostAliases:
#      - ip: "192.168.8.180"
#        hostnames:
#        - "mongodb001"
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: NAMESPACE
  labels:
    project: SERVICE_NAME
    env: NAMESPACE
    tier: TIER
    run: RUN
    subsystem: SUBSYSTEM
spec:
  selector:
    project: SERVICE_NAME
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: SERVICE_PORT
